services:
  # caddy:
  #   image: caddy:latest
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./Caddyfile:/etc/caddy/Caddyfile
  web:
    build: .
    ports:
      - "80:3000"
    volumes:
      - ./data/:/app/data/